/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbl_new;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.*;

/**
 *
 * @author ASUS
 */
public class Incoming_Vehicle extends javax.swing.JFrame {

    /**
     * Creates new form Incoming_Vehicle
     */
    static void B_Insert_Vehicle(String V_ID,String Date,String State,String Model)
        {
            System.out.println(V_ID+Date+State+Model);
            try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbl","root","pbl@123");
           // String s = " insert into vehicle(vehicle_id, date_om, model, checkin_date) values(, '2010-05-31', 'Swift', sysdate());";
            Statement st = con.createStatement();
           
          
           String query = "INSERT INTO vehicle(vehicle_id, date_om, model, checkin_date) VALUES (?, ?, ?, sysdate())";

            PreparedStatement statement = con.prepareStatement(query);
            statement.setString(1, V_ID);
            statement.setString(2, Date);
            statement.setString(3, Model);
            
            

            int rowsInserted = statement.executeUpdate();

            
            
        }
        catch(Exception e)
        {
        System.out.println(e);
        }

        }
    public Incoming_Vehicle() {
        initComponents();
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        Vehicle_ID_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Date_input = new javax.swing.JTextField();
        State_input = new javax.swing.JTextField();
        Model_input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 51));
        getContentPane().setLayout(null);

        Vehicle_ID_input.setBackground(java.awt.Color.lightGray);
        Vehicle_ID_input.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Vehicle_ID_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vehicle_ID_inputActionPerformed(evt);
            }
        });
        getContentPane().add(Vehicle_ID_input);
        Vehicle_ID_input.setBounds(359, 188, 93, 22);

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(223, 357, 229, 38);

        Date_input.setBackground(java.awt.Color.lightGray);
        Date_input.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Date_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_inputActionPerformed(evt);
            }
        });
        getContentPane().add(Date_input);
        Date_input.setBounds(359, 228, 93, 22);

        State_input.setBackground(java.awt.Color.lightGray);
        State_input.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        State_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                State_inputActionPerformed(evt);
            }
        });
        getContentPane().add(State_input);
        State_input.setBounds(359, 268, 93, 22);

        Model_input.setBackground(java.awt.Color.lightGray);
        Model_input.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(Model_input);
        Model_input.setBounds(359, 308, 93, 22);

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Vehicle Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(223, 191, 130, 16);

        jLabel2.setBackground(java.awt.Color.lightGray);
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Date (YYYY-MM-DD)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(223, 231, 118, 16);

        jLabel3.setBackground(java.awt.Color.lightGray);
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("State:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(223, 271, 130, 16);

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Model:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(223, 311, 130, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Desktop\\img3.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1, 0, 1080, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Vehicle_ID_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vehicle_ID_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vehicle_ID_inputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String V_ID = Vehicle_ID_input.getText();
          String Date = Date_input.getText();
          String State = State_input.getText();
          String Model = Model_input.getText();
          
          B_Insert_Vehicle(V_ID,Date,State,Model);
          
          setVisible(false);
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Date_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_inputActionPerformed

    private void State_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_State_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_State_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incoming_Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incoming_Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incoming_Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incoming_Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incoming_Vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date_input;
    private javax.swing.JTextField Model_input;
    private javax.swing.JTextField State_input;
    private javax.swing.JTextField Vehicle_ID_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
