/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbl_new;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import static pbl_new.Incoming_Vehicle.B_Insert_Vehicle;

/**
 *
 * @author ASUS
 */
public class worker extends javax.swing.JFrame {

    /**
     * Creates new form worker
     */
    
    static void B_Insert_Worker(String W_ID,String Name,String W_Type,String Allocated_Veh_Id)
        {
            try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbl","root","pbl@123");
           // String s = " insert into vehicle(vehicle_id, date_om, model, checkin_date) values(, '2010-05-31', 'Swift', sysdate());";
            Statement st = con.createStatement();
           
          
           String query = "INSERT INTO worker(worker_id, Name, Worker_Type,Allo_Veh_Id) VALUES (?, ?, ?, ?)";

            PreparedStatement statement = con.prepareStatement(query);
            statement.setString(1, W_ID);
            statement.setString(2, Name);
            statement.setString(3, W_Type);
            statement.setString(4, Allocated_Veh_Id);
           
            

            int rowsInserted = statement.executeUpdate();

            
            
        }
        catch(Exception e)
        {
        System.out.println(e);
        }
            
            
      }
    
    
    public worker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Input_W_ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Input_Name = new javax.swing.JTextField();
        Input_W_Type = new javax.swing.JTextField();
        Input_V_Allo_No = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Worker ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(235, 85, 139, 16);

        jLabel2.setBackground(java.awt.Color.lightGray);
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(235, 122, 139, 16);

        jLabel3.setBackground(java.awt.Color.lightGray);
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Worker Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(235, 156, 139, 16);

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Allocated Vehicle Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(235, 190, 148, 16);

        Input_W_ID.setBackground(java.awt.Color.lightGray);
        Input_W_ID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Input_W_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_W_IDActionPerformed(evt);
            }
        });
        getContentPane().add(Input_W_ID);
        Input_W_ID.setBounds(474, 82, 71, 22);

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(273, 236, 237, 23);

        Input_Name.setBackground(java.awt.Color.lightGray);
        Input_Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(Input_Name);
        Input_Name.setBounds(474, 119, 71, 22);

        Input_W_Type.setBackground(java.awt.Color.lightGray);
        Input_W_Type.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(Input_W_Type);
        Input_W_Type.setBounds(474, 153, 71, 22);

        Input_V_Allo_No.setBackground(java.awt.Color.lightGray);
        Input_V_Allo_No.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(Input_V_Allo_No);
        Input_V_Allo_No.setBounds(474, 187, 71, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Desktop\\img3.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-70, -30, 1110, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_W_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_W_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_W_IDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          String W_ID = Input_W_ID.getText();
          String Name = Input_Name.getText();
          String W_Type = Input_W_Type.getText();
          String Allocated_Vehicle = Input_V_Allo_No.getText();
          
          B_Insert_Worker(W_ID,Name,W_Type,Allocated_Vehicle);
          
          setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new worker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Input_Name;
    private javax.swing.JTextField Input_V_Allo_No;
    private javax.swing.JTextField Input_W_ID;
    private javax.swing.JTextField Input_W_Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
